version: '3'

services:
  web:
    container_name: web-nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./code:/code
      - ./default.conf:/etc/nginx/conf.d/default.conf
  php:
    container_name: web-php
    image: php:7-fpm
    volumes:
      - ./code:/code
      - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf

